[package]
name = "rcc"
version = "0.1.0"
authors = ["Kejian Chi <chiichen@qq.com>"]
license = "MIT"

[[bin]]
name = "main"

[dependencies]
llvm-sys = "140"
nom = "7.1.3"
chumsky = { version = "1.0.0-alpha.6", features = ["label"] }
ariadne = "0.3.0"
